spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./data
    username: admin
    password: admin

logging:
  file: log.log
#  jpa:
#    hibernate:
#      ddl-auto: update