spring:
  output:
    ansi:
      enabled: ALWAYS
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:oracle:thin:@localhost:49161:xe
    username: dbuser
    password: user

logging:
  file: log.log

